I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 1028, in script
    play Addie "Addie_test_audio.wav"
  File "renpy/common/000statements.rpy", line 124, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
Exception: Audio channel 'Addie' is unknown.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 1028, in script
    play Addie "Addie_test_audio.wav"
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 1971, in execute
    self.call("execute")
  File "/Applications/renpy-8.2.3-sdk/renpy/ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Applications/renpy-8.2.3-sdk/renpy/statements.py", line 349, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 124, in execute_play_music
    renpy.music.play(_audio_eval(p["file"]),
  File "/Applications/renpy-8.2.3-sdk/renpy/audio/music.py", line 103, in play
    c = get_channel(channel)
  File "/Applications/renpy-8.2.3-sdk/renpy/audio/audio.py", line 922, in get_channel
    raise Exception("Audio channel %r is unknown." % name)
Exception: Audio channel 'Addie' is unknown.

macOS-13.5-arm64-arm-64bit arm64
Ren'Py 8.2.3.24061702
Chic Boutique 1.0
Fri Jun  6 08:48:18 2025
