I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 938, in script
    Ariande "I’m guessing you’re a resident of this dorm?"
Exception: Sayer 'Ariande' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 938, in script
    Ariande "I’m guessing you’re a resident of this dorm?"
  File "C:\Users\hhall\Documents\apps\Setups\renpy-8.2.3-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\hhall\Documents\apps\Setups\renpy-8.2.3-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\hhall\Documents\apps\Setups\renpy-8.2.3-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Ariande' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
Chic Boutique 1.0
Wed Feb 26 11:27:31 2025
