I'm sorry, but an uncaught exception occurred.

While loading the script.
UnboundLocalError: local variable 'lastfn' referenced before assignment

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/main.py", line 470, in main
    renpy.game.script.load_script() # sets renpy.game.script.
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/script.py", line 359, in load_script
    self.load_appropriate_file(".rpyc", [ "_ren.py", ".rpy" ], dir, fn, initcode)
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/script.py", line 949, in load_appropriate_file
    raise Exception("Could not load file %s." % lastfn) # type: ignore
UnboundLocalError: local variable 'lastfn' referenced before assignment

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Chic Boutique 1.0
Fri May 23 20:07:59 2025
